### ISSUE TITLE
Vue Router

### ISSUE THREAD

**Issue by niallobrien** [niallobrien/vue-webpack-meteor-example#1]
Is it possible to get Vue routing working with Meteor via FlowRouter? Possibly by creating something similar to BlazeLayout or ReactLayout (called VueLayout obviously :) ).
This is all that's missing at the minute for full Vue functionality with Meteor, thanks.

**Comment by beeplin** [comment]
check this: https://github.com/Akryum/kickstart-meteor-vue-huge-app
it uses FlowRouter with vue and webpack.

Or I believe vue-router could be directly used in a similar way. No need to build something like VueLayout.
